### PR TITLE
Add KubernetesVersion param to entrypoints

### LINKED ISSUE #392: select kubernetes version
Would it make sense to have the kubernetes version as a toplevel parameter?

(I need a 1.20 kluster, I see that there is support for changing this somewere deep down, but have not yet figured out how to set it...)

### PR DESCRIPTION
**Pull request by tlindsay42**
* Closes #392
* Also add tests for each supported k8s version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by troy-ameigh — CHANGES_REQUESTED** [review]
@tlindsay42 We need to understand why you are adding the Kube Version back to the entry points. This has the potential of creating and issue for any one that is using a custom advance configuration stack, when they try and do a stack update. Also this parameter was moved to the advanced config because it is only modified approx 5% of deployments. So taking the default is the normal trend. Please revert this change or we need to have a discussion on this. Thanks

**Comment by tlindsay42** [comment]
@troy-ameigh Per our separate conversation, we're good on this front due to how I implemented this. Here's the initial screenshots from the test we discussed showing that the entrypoint's KubernetesVersion value is ignored when an advanced config set is used, as advertised in the new [entrypoint KubernetesVersion input parameter descriptions](https://github.com/aws-quickstart/quickstart-amazon-eks/blob/k8s-version/templates/amazon-eks-entrypoint-new-vpc.template.yaml#L966-L969).

#### Advanced config w/ v1.23
image

#### Entrypoint specifies v1.20 
image

#### Cluster deploys w/ advanced config set value of v1.23
image

#### Confirmed in the EKS console
image

I'll follow up in a bit when the cluster finishes deploying by updating the entrypoint KubernetesVersion value. Based on my implementation, sandbox testing, and the results of the current test, my expectation is that the change will not have an impact on the deployment.

**Comment by tlindsay42** [comment]
#### Update entrypoint KubernetesVersion value to v1.21
image

#### EKS control plane stack - cluster is still v1.23, so no impact
image

#### EKS console - cluster is still v1.23, so no impact
image

**Review by troy-ameigh — APPROVED** [review]

**Pull request merged**
