### PR TITLE
v3.0.0 release

### PR DESCRIPTION
**Pull request by jaymccon**
This PR makes the following breaking changes:

* Implement pre account and per region stacks for resources like IAM roles, CFN Macros/Resources that should be only deployed once per region/account
* Implement advanced/optional parameters being stored/resolved from parameter store instead of cfn parameters.
* Port KubeGet and KubeManifest custom resources to CFN Registry types
* Taskcat testing on PR (no more develop branch)

Once these are in we should be able to continue iterating for some time without further breaking changes.

### CODE REVIEW

**Comment by jaymccon** [comment]
I will also be using this pr to test the taskcat PR bot and setup branch rules, please don't merge/approve until I give the go ahead.

**Comment by jaymccon** [comment]
apologies on the noise on this pr, I'm using it to flush out some niggles with our new ci processes. I'd suggest any watchers that aren't interested in that to mute this.

**Comment by yanivpaz** [comment]
May I ask why EKSPrivateAccessEndpoint is removed?

**Comment by jaymccon** [comment]
> May I ask why EKSPrivateAccessEndpoint is removed?

We are in the process of moving many advanced/optional parameters into SSM Parameter Store. This gives us more headroom on the 60 parameter limit in CFN, and a cleaner launch experience for the vast majority of users who are not customizing parameters. There is now an `advanced-configuration` template that can be launched prior to launching the EKS QS, and EKSPrivateAccessEndpoint will be configurable from there.

**Comment by yanivpaz** [comment]
OK I see the new parameter 
https://github.com/aws-quickstart/quickstart-amazon-eks/blob/v3/templates/amazon-eks-advanced-configuration.template.yaml

When it will merge to master ?

**Comment by yanivpaz** [comment]
is there also new version for the user guide to install the advanced stack ?

**Comment by jaymccon** [comment]
I built draft documentation here: https://jaymccon.github.io/quickstart-amazon-eks/

**Comment by gargana** [comment]
*Instructions to review documentation changes:*

**1. Pull down repo and the Documentation changes in this Pull Request(PR):**

```bash
git clone git@github.com:/aws-quickstart/quickstart-amazon-eks.git

git fetch origin pull/162/head:v3docs_pr162

git checkout v3docs_pr162
```
You will now have a local branch _v3docs_pr162_ with the PR changes in it.

**2. Generate HTML for review**
./docs/boilerplate/.utils/generate_dynamic_content.sh && ./docs/boilerplate/.utils/build_docs.sh && open index.html

**3. Make changes as appropriate** 
repeat step 2 as necessary to double check the preview.
Annotate questions with TODO in the asciidocs as discussed.

**4. When happy with your changes**
Add changes
```
git add docs/partner_editable/
```
commit changes
```
git commit -m "_Add your commit message here_"
```
push the commits
```
git push origin v3docs_pr162
```
changes will now be in review branch _v3docs_pr162_.

**5. Leave a comment when you are done and want us to review**

**Comment by jaymccon** [comment]
🤞

**Comment by jaymccon** [comment]
stack in `cn-north-1` failed with what seemed like a transient issue, re-running

**Comment by tonynv** [comment]
Amazing work this @jaymccon @gargana

**Comment by schottsfired** [comment]
Congrats!

**Comment by ThisIsQasim** [comment]
Congratulations on the release!

**Pull request merged**
