### PR TITLE
Add v1.23 support

### PR DESCRIPTION
**Pull request by tlindsay42**
*Description of changes:*

- Add v1.23 support
- Bump auto-scaler versions to latest
- Add tests for each supported version with default parameters
- Removed Vault and Consul
- Update copyright year range
- Update .gitignore to ignore zip files & organize

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tomiszili** [comment]
Hello @tlindsay42

When will this PR will be merged?

**Comment by tlindsay42** [comment]
@tomiszili It's not ready yet. Planning on resuming focus on it soon.

**Review by troy-ameigh — APPROVED** [review]

**Comment by troy-ameigh** [comment]
Any failures in test are unrelated.

**Pull request merged**
