### PR TITLE
adds alb ingress controller and OIDC provider

### PR DESCRIPTION
**Pull request by ThisIsQasim**
*Issue #, if available:*
#86 
*Description of changes:*
Added an optional oidc provider and alb ingress controller. OIDC URL is fetched using the lambda function provided by https://github.com/bambooengineering/example-eks-oidc-iam-cloudformation. Once https://github.com/aws-quickstart/quickstart-amazon-eks-cluster-resource-provider/issues/8 is fixed we can use the stack output directly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaymccon** [comment]
This is fantastic work @ThisIsQasim ! It knowck off two big items on my wish list. 

I've addressed aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#8  and will get that update merged into this repo, once in would you mind refactoring this pr to use that?

**Comment by ThisIsQasim** [comment]
Yes I am currently going through your commit. Will rebase this PR in a couple hours.

**Comment by ThisIsQasim** [comment]
Should I continue to have the OIDC provider here as a separate template or would it be cleaner to move it to eks-resource-provider as an optional flag?

**Comment by jaymccon** [comment]
I'd vote for embedding it in the eks-controlplane stack. Ultimately the AWSQS::EKS::Cluster resource should provide a Flag to enable OIDC, so putting the custom resource as close to that resource as possible will simplify that change when it happens.

**Comment by ThisIsQasim** [comment]
Makes sense. Let me move it to the eks-controlplane stack

**Comment by ThisIsQasim** [comment]
The split & join to remove the protocol from the oidc url was failing the yaml validation check so I had to push a fix. Should I open a new PR?

**Pull request merged**
