### PR TITLE
WIP: Add Spot NodeGroup

### PR DESCRIPTION
**Pull request by ThisIsQasim**
*Issue #, if available:*
#97 
*Description of changes:*
This PR has the following changes.
- Switches the node autoscaling group to launch template instead of launch configuration.
- Adds a secondary node group for spot instances with mixed instance policy based on the [cloudbees template](https://github.com/aws-quickstart/quickstart-cloudbees-core/blob/master/templates/cloudbees-core-spot-nodes.template.yaml).
- Updates cluster autoscaler expander priority to prioritize spot instances 
- Adds [node termination handler](https://github.com/aws/aws-node-termination-handler) to handle spot interruptions.
- Removes some parameters from the root stack because of the 60 parameter limit. Should Probably wait for #162 and move them to advanced configuration template.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ThisIsQasim** [comment]
@jaymccon this is a work in progress, please review and suggest changes.

**Comment by jaymccon** [comment]
This looks great @ThisIsQasim we've had a lot of asks for spot instances, even some implementations([cloudbees-ci](https://github.com/aws-quickstart/quickstart-cloudbees-ci/blob/master/templates/cloudbees-core-addl-nodes.template.yaml)). 

Longer term we're looking at spliting out nodegroup templates, so managed nodes would have a template, regular eks-optimised ami another, suse linux another, etc. For the time being though I think putting everything into the one nodegroup stack is fine and we can split them out all at once later.

I agree that this should wait until the advanced parameters stack is in place.

**Comment by jaymccon** [comment]
going to close this as #162 adds support for spot instances by allowing you to provide a custom launch template and specify `OndemandPercentage` foir the ASG as a parameter

**Comment by ThisIsQasim** [comment]
That is good to know. Looking forward to v3

**Pull request closed without merging**
