### PR TITLE
Rafay Systems Intergration

### PR DESCRIPTION
**Pull request by troy-ameigh**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by troy-ameigh** [comment]
Can one of you please approve, Rafay is passing testing, other tests are failing. 

https://quickstart-amazon-eks-buildlogs.s3.amazonaws.com/pr/216/index.html

**Review by davmayd — APPROVED** [review]

**Review by gargana — APPROVED** [review]
LGTM. The taskcat failures were due to transient issues in well established parts of the QS that we know work well.

**Pull request merged**
