### PR TITLE
fix __init__() got an unexpected keyword argument 'snapshotRequested' (TypeError)

### PR DESCRIPTION
**Pull request by jaymccon**
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/130 https://github.com/aws-quickstart/quickstart-kubernetes-resource-provider/pull/5

*Description of changes:* update cloudformation-lib for `AWSQS::Kubernetes::Resource` and `AWSQS::Kubernetes:Get`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kolomied** [comment]
@jaymccon What would be the recommended way to apply this change to the deployed cluster? 
I have v3.0.0 deployed and I started to see this error recently. Upgrading everything to the latest main version does not look safe - I'm wondering if there is a trick you can suggest here.

**Comment by limouren** [comment]
I have a deployed cluster stack failing to delete due to this, which effectively occupied me 1 VPC in that region. Are there workarounds that I can make the deletion to proceed successfully?

**Comment by gargana** [comment]
> I have a deployed cluster stack failing to delete due to this, which effectively occupied me 1 VPC in that region. Are there workarounds that I can make the deletion to proceed successfully?

A workaround is to redeploy the "per region resource stack" with the updated resources:
* https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-per-region-resources.template.yaml 
or
* s3://aws-quickstart/quickstart-amazon-eks/templates/amazon-eks-per-region-resources.template.yaml

This will deploy the updated versions of the custom resources.

Once this stack is redeployed one should  be able to delete cleanly.

**Pull request merged**
