### PR TITLE
Pin ALB chart version and adjust IAM policy to handle the latest chart changes

### PR DESCRIPTION
**Pull request by kolomied**
*Issue #, if available:*
#320 

*Description of changes:*
The latest ALB controller chart require a change of [IAM policies](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json).

Kudos to @prashilgupta for the patch.
@gargana FYI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by prashilgupta** [comment]
How do I join this review. I don't see an option to join

**Review by jaymccon — COMMENTED** [review]
Thanks for this contribution, will get it through e2e testing shortly

**Comment by jaymccon** [comment]
fixes #320

**Review by jaymccon — APPROVED** [review]

**Pull request merged**
