### PR TITLE
implement shared resources detection

### PR DESCRIPTION
**Pull request by jaymccon**
*Description of changes:* Adds a custom resource (in its own stack) that detects and creates/updates shared resources stacks if needed. Stack updates to all resources in regional stack are ensured by passing in a random string which is then passed to each resource that could have an update (like an updated source zip).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by gargana — APPROVED** [review]
LGTM

**Comment by schottsfired** [comment]
Tested this today, it seems to be working well. Thanks for adding this!

**Pull request merged**
