### PR TITLE
Overhaul

### LINKED ISSUE #418: Cluster Cleanup No Longer Works
I've tested this many times and persistently get this error on teardown (and on each additional attempt to teardown in the console):

Screen Shot 2022-05-07 at 8 54 20 AM

And on manual teardown of the VPC, I persistently get this security group deletion warning - and it is the only resource warning once the teardown has run at least once.

Screen Shot 2022-05-07 at 8 54 52 AM

After the manual VPC delete the stack tears down properly

Perhaps a new security group was added recently and it was not added to cleanup lambdas?

### PR DESCRIPTION
**Pull request by tlindsay42**
* Closes #418 #377 #320 #310 #242
* Relates to #369 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by troy-ameigh — APPROVED** [review]

**Review by gargana — DISMISSED** [review]
LGTM - Ship it

**Review by troy-ameigh — APPROVED** [review]

**Pull request merged**
