### PR TITLE
Adding Rancher integration

### PR DESCRIPTION
**Pull request by davmayd**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaymccon** [comment]
ci logs show:
```
+ taskcat test run -s -l -m -n --dont-wait-for-delete
 _            _             _   
| |_ __ _ ___| | _____ __ _| |_ 
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_ 
 \__\__,_|___/_|\_\___\__,_|\__|
                                


·[0;30;43m[WARN   ] : No stacks were created... skipping cleanup.
·[0;30;41m[ERROR  ] : !Only 2 az's are available in us-west-1
+ EXIT=1
```

**Comment by jaymccon** [comment]
e2e tests will fail shortly, with issues unrelated to this pr (being addressed in #276), the rancher test has passed though, so I will approve.
```
rancher ap-east-1 CREATE_COMPLETE
```

**Review by jaymccon — APPROVED** [review]

**Review by gargana — APPROVED** [review]
LGTM Ship it

**Pull request merged**
