### PR TITLE
update existing vpc template to use existing subnets

### PR DESCRIPTION
**Pull request by autodidacticon**
*Description of changes:*
Updated existing VPC template to use existing subnet lists.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vsnyc** [comment]
@autodidacticon - the third subnet: `PrivateSubnet3ID` cannot be of the type: `"AWS::EC2::Subnet::Id"` since it's optional in the case of a 2-AZ deployment.

**Comment by autodidacticon** [comment]
@vsnyc thanks for the feedback. I have made the recommended changes. Where are the AZ / subnet requirements documented? Should [this section](https://aws-quickstart.github.io/quickstart-amazon-eks/#_architecture) be updated?

**Comment by vsnyc** [comment]
@autodidacticon - the architecture section represents the desired state and we do want a 3-AZ deployment where possible as a best practice. And that was the original state of the code. 2-AZ option was added later to allow for deployments in AWS Regions that don't have three at least three Availability Zones (for example, us-west-1 and some of the GovCloud and China Region partitions). The best option would be to update the parameter description of `NumberOfAZs` and `AvailabilityZones` parameters to reflect this. Please push the commit that changes `PrivateSubnet3ID` back to `String` so we can accept this PR. Thanks!

**Comment by autodidacticon** [comment]
@vsnyc it looks like those parameters are only present within the new vpc template. Pushed the changes you suggested with one additional update.

**Review by jaymccon — APPROVED** [review]
LGTM. No need for e2e as it does not test the existing vpc entrypoint.

**Comment by autodidacticon** [comment]
I can't merge this.

**Pull request merged**
