### PR TITLE
Update to new AWS Load Balancer controller

### PR DESCRIPTION
**Pull request by jaymccon**
copy of #239 that retains the parameter names for backwards compatibility. Parameter lables have been left with the new, updated labels.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaymccon** [comment]
@ThisIsQasim lmk if you have any feedback on this

**Comment by ThisIsQasim** [comment]
@jaymccon You can create a PR from the first [commit](https://github.com/aws-quickstart/quickstart-amazon-eks/commit/ea0f08a25b98e4ae8f2adcae1fe72637149028c0) directly since it basically does the same thing. Right now the second and third commits rename the params and the forth one reverts them. 
Just a minor detail. Should work either way.

**Review by troy-ameigh — DISMISSED** [review]

**Comment by jaymccon** [comment]
looking at the build log the error:

```
LoadBalancerControllerHelmChart
resource creation timed out
LastKnownErrors: Deployment is not ready: kube-system/aws-load-balancer-controller-1605037586. 0 out of 1 expected pods are ready
```
for the windows test likely indicates that the chart is trying to schedule pods to the windows nodes.

**Review by gargana — APPROVED** [review]
LGTM - ship it

**Pull request merged**
