### PR TITLE
HashiCorp Consul and Vault on EKS integration

### PR DESCRIPTION
**Pull request by gargana**
*Adding Vault and Consul to the EKS Quick Start:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yanivpaz** [comment]
I don't think that hashicorp modules should be part of core eks templates or eks repo at all
it will make the templates cumbersome and hard to maintain

**Comment by phenri00** [comment]
> I don't think that hashicorp modules should be part of core eks templates or eks repo at all
> it will make the templates cumbersome and hard to maintain

I agree. This Quickstart starts to get bloated.

**Comment by jaymccon** [comment]
@yanivpaz @phenri00 can we continue this discussion in #206. 

For the time being this is most likely going to be merged, but it would be great if we could find a way to better de-couple 3rd party addins like this.

**Pull request merged**
