### PR TITLE
Add missing permission and use distinct role for VPC proxy function

### PR DESCRIPTION
**Pull request by gargana**
*Description of changes:*
Add missing IAM permission to AWSQS::Kubernetes::Resource IAM Role.
Create a distinct IAM policy for the AWSQS::Kubernetes::Resource VPC proxy lambda

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by tlindsay42 — APPROVED** [review]

**Comment by gargana** [comment]
Need to split this fix over 2 distinct changes. 
Starting over to keep history clean

**Pull request merged**
