### PR TITLE
Retain IRSA resources on delete.

### PR DESCRIPTION
**Pull request by vsnyc**
*Issue #, if available:* https://github.com/aws-quickstart/quickstart-amazon-eks/issues/378

*Description of changes:*
Added DeletionPolicy: Retain for resources

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaymccon** [comment]
lgtm, @vsnyc as you are not in `CODEOWNERS` the bot will ignore you 😸

**Review by jaymccon — APPROVED** [review]

**Comment by jaymccon** [comment]
I think this is small enough to merge without e2e, your call @troy-ameigh

**Comment by troy-ameigh** [comment]
merged

--

Troy Ameigh
Sr. Partner Solutions Architect
Amazon Web Services
M: (512)201-0430
Email: ***@***.******@***.***>

[signature_1055417700]

[signature_24346680]<https://www.youracclaim.com/badges/9441f5cd-c21b-4c41-829b-07906ccc7bcc/public_url>[signature_1275957190]<https://www.youracclaim.com/badges/6e89fb3b-8b3b-40ed-9558-50129de22714/public_url>[signature_406581155]<https://www.youracclaim.com/badges/f1f7a8cb-5f0d-4de7-b286-4dbecdba9c98/public_url>[signature_1240399854]<https://www.youracclaim.com/badges/aad71e34-b480-47f3-a315-34693d668bdb/public_url>[signature_301210233]<https://www.youracclaim.com/badges/90e436f3-b80c-4a5d-aa7d-fd4b3045ef4e/public_url>

Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=ameighta&fn=Troy&ln=Ameigh>.


From: Jay McConnell ***@***.***>
Reply-To: aws-quickstart/quickstart-amazon-eks ***@***.***>
Date: Wednesday, November 17, 2021 at 11:47 AM
To: aws-quickstart/quickstart-amazon-eks ***@***.***>
Cc: "Ameigh, Troy" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-quickstart/quickstart-amazon-eks] Retain IRSA resources on delete. (PR #379)


I think this is small enough to merge without e2e, your call @troy-ameigh<https://github.com/troy-ameigh>

**Pull request merged**
